# Cloud Build configuration for deploying to GCP Cloud Run
steps:
  # Build the Spring Boot application
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/brand-voice-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/brand-voice-service:latest'
      - '.'
    id: 'build-service'

  # Build the NLP Analyzer
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nlp-analyzer:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nlp-analyzer:latest'
      - './nlp-analyzer'
    id: 'build-nlp'

  # Build the API Gateway
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api-gateway:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api-gateway:latest'
      - './api-gateway'
    id: 'build-gateway'

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/brand-voice-service:$COMMIT_SHA']
    id: 'push-service'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nlp-analyzer:$COMMIT_SHA']
    id: 'push-nlp'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-gateway:$COMMIT_SHA']
    id: 'push-gateway'

  # Deploy NLP Analyzer to Cloud Run (no external access)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nlp-analyzer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nlp-analyzer:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'LOG_LEVEL=INFO'
    id: 'deploy-nlp'

  # Deploy Brand Voice Service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'brand-voice-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/brand-voice-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '50'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod,DB_HOST=${_DB_HOST},REDIS_HOST=${_REDIS_HOST},NLP_ANALYZER_URL=${_NLP_URL}'
      - '--set-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
    id: 'deploy-service'

  # Deploy API Gateway to Cloud Run (public)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-gateway'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api-gateway:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'BRAND_VOICE_SERVICE_URL=${_SERVICE_URL}'
    id: 'deploy-gateway'

# Substitutions (set in Cloud Build trigger)
substitutions:
  _DB_HOST: 'cloudsql-proxy'
  _REDIS_HOST: 'redis-instance'
  _NLP_URL: 'https://nlp-analyzer-hash-uc.a.run.app'
  _SERVICE_URL: 'https://brand-voice-service-hash-uc.a.run.app'
  _CLOUDSQL_INSTANCE: 'project:region:instance'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'